package org.example;// Generated by Selenium IDE

import org.junit.Test;

public class JutsuTest extends TestBase {

  @Test
  public void jutsuTestLogin() {
    applicationManager.getNavigationHelper().openHomePage();
    applicationManager.getLoginHelper().login(new Account("PoshKamil", "danisdanis"));
  }

  @Test
  public void jutsuTestSendMessage() {
    applicationManager.getNavigationHelper().openHomePage();
    applicationManager.getLoginHelper().login(new Account("PoshKamil", "danisdanis"));
    applicationManager.getMessageHelper().sendMessage(new Message("Danis"));

  }
}
